### PR TITLE
ci(actions): add cross-platform test jobs

### PR DESCRIPTION
**Pull request by Cphayim**
- Add cross-platform test jobs to CI workflows

### CODE REVIEW

**Comment by Cphayim** [comment]
Something strange happened in the tests on Node 14, two errors are reported when using dynamic import:
image
image
However, switching to version 14 locally to run the tests will have occasional success, and it is suspected that there is a problem with jest using the VM to load the ESM

**Comment by Cphayim** [comment]
This is the local test success and failure under version 14
image
image

**Comment by Hoyoe** [comment]
I looked at the actions, and the tests in Node 16 all passed, Is it a `--experimental-vm-modules` inconsistency used by jest?

**Comment by Cphayim** [comment]
Maybe, a headache 😂 I'm trying vitest, wish me luck

**Comment by Cphayim** [comment]
Passed #10 , give it up

**Pull request closed without merging**
